// <auto-generated />
using System;
using BearPetManagement_Repository.ApplicationDatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BearPetManagement_Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109012819_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BearPetManagement_Repository.Models.BearAccount", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID")
                        .HasName("PK_Account");

                    b.ToTable("BearAccounts");
                });

            modelBuilder.Entity("BearPetManagement_Repository.Models.BearType", b =>
                {
                    b.Property<int>("BearTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BearTypeId"));

                    b.Property<string>("BearTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BearTypeId")
                        .HasName("PK_BearType");

                    b.ToTable("BearTypes");
                });

            modelBuilder.Entity("BearPetManagement_Repository.NewFolder.BearProfile", b =>
                {
                    b.Property<int>("BearProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BearTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BearWeight")
                        .HasColumnType("int");

                    b.Property<string>("CareNeeds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date");

                    b.HasKey("BearProfileId")
                        .HasName("PK_BearProfile");

                    b.ToTable("BearProfiles");
                });

            modelBuilder.Entity("BearPetManagement_Repository.NewFolder.BearProfile", b =>
                {
                    b.HasOne("BearPetManagement_Repository.Models.BearType", "BearType")
                        .WithMany("BearProfiles")
                        .HasForeignKey("BearProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BearProfile_BearType");

                    b.Navigation("BearType");
                });

            modelBuilder.Entity("BearPetManagement_Repository.Models.BearType", b =>
                {
                    b.Navigation("BearProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
