// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("BearType")]
public partial class BearType
{
    [Key]
    public int BearTypeId { get; set; }

    [StringLength(250)]
    public string BearTypeName { get; set; }

    [StringLength(250)]
    public string Origin { get; set; }

    [StringLength(1000)]
    public string Description { get; set; }

    [InverseProperty("BearType")]
    public virtual ICollection<BearProfile> BearProfiles { get; set; } = new List<BearProfile>();
}