// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

[Table("BearProfile")]
public partial class BearProfile
{
    [Key]
    public int BearProfileId { get; set; }

    public int BearTypeId { get; set; }

    [Required]
    [StringLength(150)]
    public string BearName { get; set; }

    public double BearWeight { get; set; }

    [Required]
    [StringLength(2000)]
    public string Characteristics { get; set; }

    [Required]
    [StringLength(2000)]
    public string CareNeeds { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [ForeignKey("BearTypeId")]
    [InverseProperty("BearProfiles")]
    public virtual BearType BearType { get; set; }
}