// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class BearProfile
{
    public int BearProfileId { get; set; }

    public string BearName { get; set; }

    public int? BearWeight { get; set; }

    public string Characteristics { get; set; }

    public string CareNeeds { get; set; }

    public DateOnly? ModifiedDate { get; set; }
}