// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class BearProfile
{
    public int BearProfileId { get; set; }

    public int BearTypeId { get; set; }

    [RegularExpression(@"^([A-Z0-9][a-zA-Z0-9#]*\s)*([A-Z0-9][a-zA-Z0-9#]*)$",
ErrorMessage = "BearName must start with uppercase letter or number, and can contain letters, numbers, # and spaces")]
    public string BearName { get; set; }

    [Range(200, 10000000000, ErrorMessage = "weight must be greater than 200")]
    public double BearWeight { get; set; }

    public string Characteristics { get; set; }

    public string CareNeeds { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual BearType BearType { get; set; }
}