// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repository.Models;

public partial class FA25BearDBContext : DbContext
{
    public FA25BearDBContext()
    {
    }

    public FA25BearDBContext(DbContextOptions<FA25BearDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BearAccount> BearAccounts { get; set; }

    public virtual DbSet<BearProfile> BearProfiles { get; set; }

    public virtual DbSet<BearType> BearTypes { get; set; }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}