// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PE_PRN232_FA25_NguyenThaiDuy_BE.Repositories.Models;

public partial class BearProfile
{

    [Key]
    public int BearProfileId { get; set; }

    public int BearTypeId { get; set; }

    public string BearName { get; set; }

    public double BearWeight { get; set; }

    public string Characteristics { get; set; }

    public string CareNeeds { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual BearType BearType { get; set; }
}