<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FA25Bear.DataAccess\FA25Bear.DataAccess.csproj" />
    <ProjectReference Include="..\FA25Bear.Service\FA25Bear.Service.csproj" />
  </ItemGroup>

</Project>
