// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repository.Models;

public partial class BearProfile
{
    public int BearProfileId { get; set; }
    [Required]
    public int BearTypeId { get; set; }
	[Required]
	[MinLength(4, ErrorMessage = "MinLength for BearName is 4")]
	[MaxLength(50, ErrorMessage = "MaxLength for BearName is 50")]
	[RegularExpression(
	@"^([A-Z0-9][a-zA-Z0-9#]*\s)*([A-Z0-9][a-zA-Z0-9#]*)$",
	ErrorMessage = "BearName format is invalid."
)]
	public string BearName { get; set; }
	[Required]
	[Range(200, double.MaxValue, ErrorMessage = "BearWeight must be greater than 200.")]
	public double BearWeight { get; set; }
	[Required]
	public string Characteristics { get; set; }
	[Required]
	public string CareNeeds { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual BearType BearType { get; set; }
}