// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(BearManagementDbContext))]
    partial class BearManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repositories.Models.BearAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AccountId")
                        .HasName("PK__BearAc__349DA58674FFF6D7");

                    b.ToTable("BearAccounts");
                });

            modelBuilder.Entity("Repositories.Models.BearProfile", b =>
                {
                    b.Property<int>("BearProfileId")
                        .HasColumnType("int")
                        .HasColumnName("BearProfileID");

                    b.Property<string>("BearName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("BearTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BearTypeId");

                    b.Property<int>("BearWeight")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("CareNeeds")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("ModifiedDate")
                        .HasColumnType("date");

                    b.HasKey("BearProfileId")
                        .HasName("PK__BearProfile__785BD69FF3D8930C");

                    b.HasIndex("BearTypeId");

                    b.ToTable("BearProfile", (string)null);
                });

            modelBuilder.Entity("Repositories.Models.BearType", b =>
                {
                    b.Property<int>("BearTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BearTypeId");

                    b.Property<string>("BearTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("BearTypeId")
                        .HasName("PK__BearType__DAD4F3BE33E09654");

                    b.ToTable("BearType", (string)null);
                });

            modelBuilder.Entity("Repositories.Models.BearProfile", b =>
                {
                    b.HasOne("Repositories.Models.BearType", "BearType")
                        .WithMany("BearProfiles")
                        .HasForeignKey("BearTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_BearProfile_brand");

                    b.Navigation("BearType");
                });

            modelBuilder.Entity("Repositories.Models.BearType", b =>
                {
                    b.Navigation("BearProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
