// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repositories.ThienNH.Models;

public partial class BearProfile
{
    public int BearProfileId { get; set; }

    public int BearTypeId { get; set; }

    [Required(ErrorMessage = "BearName is required")]
    [Unicode(false)]
    [RegularExpression(@"^([A-Z0-9][a-zA-Z0-9#]*\s)*([A-Z0-9][a-zA-Z0-9#]*)$",
      ErrorMessage = "BearName must start with an uppercase letter or digit, and can only contain letters, digits, #, and spaces between words")]
    public string BearName { get; set; }

    [Required(ErrorMessage = "Weight is required")]
    [Range(200, int.MaxValue, ErrorMessage = "Weight must be greater than 200")]
    public double Weight { get; set; }

    public string Characteristics { get; set; }

    public string CareNeeds { get; set; }

    public DateTime ModifiedDate { get; set; }

    public virtual BearType BearType { get; set; }
}