// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class BearType
{
    public string BearTypeId { get; set; }

    public string BearTypeName { get; set; }

    public string Orgin { get; set; }

    public string Description { get; set; }

    public virtual ICollection<BearProfile> BearProfiles { get; set; } = new List<BearProfile>();
}