// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class BearProfile
{
    public int BearProfileId { get; set; }

    public string BearName { get; set; }

    public double BearWeight { get; set; }

    public string Characteristics { get; set; }

    public bool CareNeeds { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string BearTypeId { get; set; }

    public virtual BearType BearType { get; set; }
}