// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PE_PRN232_FA25_NguyenQuangMinh_BE.Repo.Models;

public partial class BearType
{
    [Key]
    public int BearTypeId { get; set; }

    public string BearTypeName { get; set; }

    public string Origin { get; set; }

    public string Description { get; set; }

    public virtual ICollection<BearProfile> BearProfiles { get; set; } = new List<BearProfile>();
}