// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PE_PRN232_FA25_NguyenQuangMinh_BE.Repo.Models;

public partial class BearProfile
{
    [Key]
    public int BearProfileId { get; set; }

    public int? BearTypeId { get; set; }
    [Required]
    public string BearName { get; set; }
    [Required]
    public string BearWeight { get; set; }

    public string Characteristics { get; set; }

    public string CareNeed { get; set; }

    public DateOnly? ModifiedDate { get; set; }

    public virtual BearType BearType { get; set; }
}