// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PE_PRN232_FA25_NguyenQuangMinh_BE.Repo.Models;

public partial class BearAccount
{
    public int AccountId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? Role { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }
}